### ISSUE TITLE
java.lang.NullPointerException error

### ISSUE THREAD

**Issue by Behnamjef** [hojjatjafary/CafebazaarUnity#8]
Hi,
The SDK works fine but we have this error on our analytics:

java.lang.NullPointerException
	at com.bazaar.util.IabHelper.queryPurchases(IabHelper.java:986)
	at com.bazaar.util.IabHelper.queryInventory(IabHelper.java:544)
	at com.bazaar.util.IabHelper.queryInventory(IabHelper.java:522)
	at com.bazaar.util.IabHelper$2.run(IabHelper.java:617)
	at java.lang.Thread.run(Thread.java:841)

what can we do about it?

**Comment by hojjatjafary** [comment]
You can check the source code and try to find the issue and after you found that send me a pull request to share the fix with other users!

**Comment by Behnamjef** [comment]
Thanks for your quick response, I'm a Unity developer and I don't have enough knowledge for doing this. but I give it a try. thanks.
